### ISSUE TITLE
I can't get this to work at all. Errors out

### ISSUE THREAD

**Issue by gandhiShepard** [shakyShane/gulp-svg-sprites#74]
I get this error when I run 'gulp sprites' 
```
[10:00:58] TypeError: undefined is not a function
    at Gulp.<anonymous> (/Users/ben/Desktop/blah/gulpfile.js:9:9)
    at module.exports (/Users/ben/Desktop/blah/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ben/Desktop/blah/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ben/Desktop/blah/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/ben/Desktop/blah/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
```

And I get these warnings while I try to install:
```
../vendor/libxml/xpath.c:12402:13: warning: comparison of constant
      'XML_NAMESPACE_DECL' (18) with expression of type 'xmlXPathTypeVal' is
      always false [-Wtautological-constant-out-of-range-compare]
                        if (type == XML_NAMESPACE_DECL)
                            ~~~~ ^  ~~~~~~~~~~~~~~~~~~
In file included from ../vendor/libxml/xpath.c:185:
../vendor/libxml/trionan.c:194:1: warning: unused function
      'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative'
      [-Wunused-function]
trio_is_negative
^
```

please advise, I'd LOVE to get this working!

**Comment by gandhiShepard** [comment]
Sorry. I didn't notice that I was on the old README page. My bad.
